server:
  port: 8084

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    from: javagroup638@gmail.com
    password: bvctchfyyixyswhh
    subject: Currency exchange confirmation
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  async:
    thread-pool: 4
app:
  rabbit:
    queueName: send_email_data

