server:
  port: 8084

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: marcin.miaso.programista@gmail.com
    password: gshfpnuyrvglifjp
    subject: Currency exchange confirmation
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  async:
    thread-pool: 4
app:
  rabbit:
    queue-name: send_email_data_queue

